### ISSUE TITLE
can't open pak version 12

### ISSUE THREAD

**Issue by Chuanhsing** [jashking/UnrealPakViewer#37]
can't open pak version 12

**Comment by Liujunhua007** [comment]
Invalid pak file version (14) in 'C:/Program Files/Hotta/Client/WindowsNoEditor/Hotta/Content/Paks/pakchunk0optional-WindowsNoEditor.pak'. 
when i load a file of hotta(tower of fantasy 4.0)...

**Comment by Dushess** [comment]
there is info about max archives version support, it's 10. SO you need to recompile this toolkit from sourecs.
