### ISSUE TITLE
我不知道怎么打开窗口

### ISSUE THREAD

**Issue by euphoriaer** [jashking/UnrealPakViewer#5]
我找不到怎么打开编辑窗口，编译完成之后，如何打开编辑器窗口

**Comment by euphoriaer** [comment]
我怀疑自己是不是应该从源码编译，但是我下载25.3的源码编译会产生错误，作者的安装说明太过简略

**Comment by jashking** [comment]
在vs工程里把UnrealPakViewer设置为启动项，然后运行，或者到Engine\Binaries下找到UnrealPakViewer.exe运行

**Comment by jashking** [comment]
不知道怎么编译的话直接下载Release包运行即可
[v1.0](https://github.com/jashking/UnrealPakViewer/releases)

**Comment by euphoriaer** [comment]
感谢，已经解决

**Comment by jashking** [comment]
solved
