### ISSUE TITLE
win10打不开

### ISSUE THREAD

**Issue by qingkong143** [jashking/UnrealPakViewer#53]
![Screenshot_20241018_185250](https://github.com/user-attachments/assets/8ace404a-8dd2-4019-ac7e-cc9fd1736a02)
文件缺失

**Comment by jashking** [comment]
装下 vc runtime
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist?view=msvc-170

**Comment by qingkong143** [comment]
解决了，谢谢
