### ISSUE TITLE
It just closes

### ISSUE THREAD

**Issue by pinguluk** [jashking/UnrealPakViewer#8]
When I try to open a .pak, it just closes.

**Comment by jashking** [comment]
you can see the log to find why it crashed

**Comment by pinguluk** [comment]
I can't find the log, where can I find it?

**Comment by jashking** [comment]
C:\Users\[YourAccountName]\AppData\Local\UnrealPakViewer\Saved\Logs

**Comment by pinguluk** [comment]
[UnrealPakViewer.log](https://github.com/jashking/UnrealPakViewer/files/6423400/UnrealPakViewer.log)

**Comment by jashking** [comment]
the precompiled version was compiled with UE 4.26.0, which max compatible pak file version is 10, and can't open pak files which version is 11,  so you have to compile UnrealPakViewer by yourself
